[package]
name = "cronet-rs"
version = "0.0.1"
edition = "2021"
authors = ["Sleeyax"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.16.0"

[build-dependencies]
bindgen = "0.60.1"
