name: Generate Sponsors README
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0-6
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate sponsors
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PAT }}
          file: "README.md"
          minimum: 2500 # >= Supercharged tier ($25)
      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: "."
